# Generated by scripts/update-sources.sh from libmalloc.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <libmalloc>/libmalloc.xcodeproj/project.pbxproj libsystem_malloc --nix
#
# Paths are relative to the libmalloc source root.
[
  "resolver/resolver.c"
  "src/bitarray.c"
  "src/early_malloc.c"
  "src/frozen_malloc.c"
  "src/has_section.c"
  "src/instrumentation.c"
  "src/legacy_malloc.c"
  "src/magazine_large.c"
  "src/magazine_malloc.c"
  "src/magazine_medium.c"
  "src/magazine_rack.c"
  "src/magazine_small.c"
  "src/magazine_tiny.c"
  "src/magmallocProvider.d"
  "src/malloc.c"
  "src/malloc_common.c"
  "src/malloc_config.c"
  "src/malloc_printf.c"
  "src/malloc_type.c"
  "src/msl_lite_support.c"
  "src/nano_malloc_common.c"
  "src/nanov2_malloc.c"
  "src/pgm_malloc.c"
  "src/purgeable_malloc.c"
  "src/sanitizer_malloc.c"
  "src/stack_trace.c"
  "src/vm.c"
  "src/wrapper_zones.c"
  "src/xzone_malloc/xzone_introspect.c"
  "src/xzone_malloc/xzone_malloc.c"
  "src/xzone_malloc/xzone_metapool.c"
  "src/xzone_malloc/xzone_segment.c"
]
