# Generated by scripts/update-sources.sh from Libm.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <Libm>/Libm.xcodeproj/project.pbxproj libmathCommon.o --nix
#
# Paths are relative to the Libm source root.
[
  "Source/Intel/e_remquol.s"
  "Source/Intel/exp2.s"
  "Source/Intel/fenv.c"
  "Source/Intel/fmaxfminfdim.s"
  "Source/Intel/log.s"
  "Source/Intel/modff.s"
  "Source/Intel/nan.c"
  "Source/Intel/nextafter.s"
  "Source/Intel/nextafterf.s"
  "Source/Intel/xmm_exp.c"
  "Source/Intel/xmm_misc.c"
  "Source/Intel/xmm_remainder.c"
  "Source/PowerPC/expTable.c"
  "Source/PowerPC/fenv.c"
  "Source/PowerPC/fpmacros.c"
  "Source/PowerPC/logTable.c"
  "Source/PowerPC/minmaxdim.c"
  "Source/PowerPC/nan.c"
  "Source/PowerPC/nextafter.c"
  "Source/PowerPC/remmod.c"
  "Source/PowerPC/rndint.c"
  "Source/PowerPC/tableExpD.c"
  "Source/PowerPC/tableLogD.c"
]
