# Generated by scripts/update-sources.sh from libpthread.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <libpthread>/libpthread.xcodeproj/project.pbxproj libsystem_pthread --nix
#
# Paths are relative to the libpthread source root.
[
  "src/pthread.c"
  "src/pthread_asm.s"
  "src/pthread_atfork.c"
  "src/pthread_cancelable.c"
  "src/pthread_cond.c"
  "src/pthread_cwd.c"
  "src/pthread_dependency.c"
  "src/pthread_mutex.c"
  "src/pthread_rwlock.c"
  "src/pthread_tsd.c"
  "src/qos.c"
  "src/resolver/resolver.c"
  "src/variants/pthread_cancelable_cancel.c"
]
