# Generated by scripts/update-sources.sh from text_cmds.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <text_cmds>/text_cmds.xcodeproj/project.pbxproj <tool>
#
# One attribute per target. Paths are relative to the text_cmds source root.
{
  banner = [
    "banner/banner.c"
  ];
  bintrans = [
    "bintrans/apple_base64.c"
    "bintrans/bintrans.c"
    "bintrans/qp.c"
    "bintrans/uudecode.c"
    "bintrans/uuencode.c"
  ];
  cat = [
    "cat/cat.c"
  ];
  col = [
    "col/col.c"
  ];
  colrm = [
    "colrm/colrm.c"
  ];
  column = [
    "column/column.c"
  ];
  comm = [
    "comm/comm.c"
  ];
  csplit = [
    "csplit/csplit.c"
  ];
  cut = [
    "cut/cut.c"
  ];
  ed = [
    "ed/buf.c"
    "ed/glbl.c"
    "ed/io.c"
    "ed/main.c"
    "ed/re.c"
    "ed/sub.c"
    "ed/undo.c"
  ];
  expand = [
    "expand/expand.c"
  ];
  fmt = [
    "fmt/fmt.c"
  ];
  fold = [
    "fold/fold.c"
  ];
  grep = [
    "grep/file.c"
    "grep/grep.c"
    "grep/queue.c"
    "grep/util.c"
  ];
  head = [
    "head/head.c"
  ];
  join = [
    "join/join.c"
  ];
  lam = [
    "lam/lam.c"
    "tests/sort_vers.c"
  ];
  look = [
    "look/look.c"
  ];
  md5 = [
    "md5/md5.c"
  ];
  nl = [
    "nl/nl.c"
  ];
  paste = [
    "paste/paste.c"
  ];
  pr = [
    "pr/egetopt.c"
    "pr/pr.c"
  ];
  rev = [
    "rev/rev.c"
  ];
  rs = [
    "rs/rs.c"
  ];
  sed = [
    "sed/compile.c"
    "sed/main.c"
    "sed/misc.c"
    "sed/process.c"
  ];
  sort = [
    "sort/bwstring.c"
    "sort/coll.c"
    "sort/file.c"
    "sort/mem.c"
    "sort/radixsort.c"
    "sort/sort.c"
    "sort/vsort.c"
  ];
  split = [
    "split/split.c"
  ];
  tail = [
    "tail/forward.c"
    "tail/misc.c"
    "tail/read.c"
    "tail/reverse.c"
    "tail/tail.c"
  ];
  tr = [
    "tr/cmap.c"
    "tr/cset.c"
    "tr/str.c"
    "tr/tr.c"
  ];
  ul = [
    "ul/ul.c"
  ];
  unexpand = [
    "unexpand/unexpand.c"
  ];
  uniq = [
    "uniq/uniq.c"
  ];
  unvis = [
    "unvis/unvis.c"
  ];
  vis = [
    "vis/foldit.c"
    "vis/vis.c"
  ];
}
