# Generated by scripts/update-sources.sh from shell_cmds.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <shell_cmds>/shell_cmds.xcodeproj/project.pbxproj <tool>
#
# One attribute per target. Paths are relative to the shell_cmds source root.
{
  echo = [
    "echo/echo.c"
  ];
  pwd = [
    "pwd/pwd.c"
  ];
  uname = [
    "uname/uname.c"
  ];
  who = [
    "who/who.c"
  ];
}
