# Generated by scripts/update-sources.sh from file_cmds.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <file_cmds>/file_cmds.xcodeproj/project.pbxproj <tool>
#
# One attribute per target. Paths are relative to the file_cmds source root.
{
  chflags = [
    "chflags/chflags.c"
  ];
  chmod = [
    "chmod/chmod.c"
    "chmod/chmod_acl.c"
  ];
  chown = [
    "chown/chown.c"
  ];
  cp = [
    "cp/cp.c"
    "cp/utils.c"
  ];
  du = [
    "du/du.c"
  ];
  ln = [
    "ln/ln.c"
  ];
  ls = [
    "ls/cmp.c"
    "ls/ls.c"
    "ls/print.c"
    "ls/util.c"
  ];
  mkdir = [
    "mkdir/mkdir.c"
  ];
  mv = [
    "mv/mv.c"
  ];
  stat = [
    "stat/stat.c"
  ];
  truncate = [
    "truncate/truncate.c"
  ];
  xattr = [
    "xattr/xattr.c"
  ];
}
