# Generated by scripts/update-sources.sh from file_cmds.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <file_cmds>/file_cmds.xcodeproj/project.pbxproj <tool>
#
# One attribute per target. Paths are relative to the file_cmds source root.
{
  ls = [
    "ls/cmp.c"
    "ls/ls.c"
    "ls/print.c"
    "ls/util.c"
  ];
}
