# Generated by scripts/update-sources.sh from libmd.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <libmd>/libmd.xcodeproj/project.pbxproj libmd --nix
#
# Paths are relative to the libmd source root.
[
  "$(BUILT_PRODUCTS_DIR)/md4hl.c"
  "$(BUILT_PRODUCTS_DIR)/md5hl.c"
  "$(BUILT_PRODUCTS_DIR)/sha1hl.c"
  "$(BUILT_PRODUCTS_DIR)/sha224hl.c"
  "$(BUILT_PRODUCTS_DIR)/sha256hl.c"
  "$(BUILT_PRODUCTS_DIR)/sha384hl.c"
  "$(BUILT_PRODUCTS_DIR)/sha512hl.c"
  "$(BUILT_PRODUCTS_DIR)/shahl.c"
  "libmd/sha0c.c"
]
