# Generated by scripts/update-sources.sh from system_cmds.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <system_cmds>/system_cmds.xcodeproj/project.pbxproj <tool>
#
# One attribute per target. Paths are relative to the system_cmds source root.
{
  ac = [
    "ac/ac.c"
  ];
  accton = [
    "accton/accton.c"
  ];
  dmesg = [
    "dmesg/dmesg.c"
  ];
  getconf = [
    "$(BUILT_PRODUCTS_DIR)/confstr.c"
    "$(BUILT_PRODUCTS_DIR)/limits.c"
    "$(BUILT_PRODUCTS_DIR)/pathconf.c"
    "$(BUILT_PRODUCTS_DIR)/progenv.c"
    "$(BUILT_PRODUCTS_DIR)/sysconf.c"
    "$(BUILT_PRODUCTS_DIR)/unsigned_limits.c"
    "getconf/getconf.c"
  ];
  hostinfo = [
    "hostinfo/hostinfo.c"
  ];
  mkfile = [
    "mkfile/mkfile.c"
  ];
  nologin = [
    "nologin/nologin.c"
  ];
  pwd_mkdb = [
    "pwd_mkdb/pw_scan.c"
    "pwd_mkdb/pwd_mkdb.c"
  ];
  sa = [
    "sa/db.c"
    "sa/main.c"
    "sa/pdb.c"
    "sa/usrdb.c"
  ];
  sync = [
    "sync/sync.c"
  ];
  sysctl = [
    "sysctl/sysctl.c"
  ];
  vm_stat = [
    "vm_stat/vm_stat.c"
  ];
  wait4path = [
    "wait4path/wait4path.c"
    "wait4path/wait4path.version"
  ];
  zdump = [
    "zdump/zdump.c"
  ];
  zic = [
    "zic/zic.c"
  ];
}
