/* SPDX-License-Identifier: MIT
 * Keep the registered provider separate from XNU's early-boot primitives.
 */
#pragma once
#define aes_set_encrypt_key_generic md_aes_set_encrypt_key_generic
#define aes_set_decrypt_key_generic md_aes_set_decrypt_key_generic
#define aes_encrypt_generic md_aes_encrypt_generic
#define aes_decrypt_generic md_aes_decrypt_generic
#define aes_set_encrypt_key_internal md_aes_set_encrypt_key_internal
#define aes_set_decrypt_key_internal md_aes_set_decrypt_key_internal
#define aes_encrypt_internal md_aes_encrypt_internal
#define aes_decrypt_internal md_aes_decrypt_internal
#define ccdigest_init md_ccdigest_init
#define ccdigest_update md_ccdigest_update
#define ccdigest md_ccdigest
#define ccdigest_parallel md_ccdigest_parallel
#define cchmac_init md_cchmac_init
#define cchmac_update md_cchmac_update
#define cchmac_final md_cchmac_final
#define cchmac md_cchmac
#define ccsha1_ltc_di md_ccsha1_ltc_di
#define ccsha256_ltc_di md_ccsha256_ltc_di
#define ccsha384_ltc_di md_ccsha384_ltc_di
#define ccsha512_ltc_di md_ccsha512_ltc_di
#define ccsha1_di md_ccsha1_di
#define ccsha256_di md_ccsha256_di
#define ccsha384_di md_ccsha384_di
#define ccsha512_di md_ccsha512_di
#define ccdrbg_factory_nisthmac md_ccdrbg_factory_nisthmac
#define ccdrbg_init md_ccdrbg_init
#define ccdrbg_reseed md_ccdrbg_reseed
#define ccdrbg_generate md_ccdrbg_generate
#define ccdrbg_done md_ccdrbg_done
#define ccdrbg_context_size md_ccdrbg_context_size
#define ccdrbg_must_reseed md_ccdrbg_must_reseed
#define cc_clear md_cc_clear
#define explicit_bzero md_explicit_bzero
#define SHA1_Init md_SHA1_Init
#define SHA1_Update md_SHA1_Update
#define SHA1_Final md_SHA1_Final
#define SHA1_Transform md_SHA1_Transform
#define SHA1 md_SHA1
#define SHA224_Init md_SHA224_Init
#define SHA224_Update md_SHA224_Update
#define SHA224_Final md_SHA224_Final
#define SHA224_Transform md_SHA224_Transform
#define SHA224 md_SHA224
#define SHA256_Init md_SHA256_Init
#define SHA256_Update md_SHA256_Update
#define SHA256_Final md_SHA256_Final
#define SHA256_Transform md_SHA256_Transform
#define SHA256 md_SHA256
#define SHA384_Init md_SHA384_Init
#define SHA384_Update md_SHA384_Update
#define SHA384_Final md_SHA384_Final
#define SHA384_Transform md_SHA384_Transform
#define SHA384 md_SHA384
#define SHA512_Init md_SHA512_Init
#define SHA512_Update md_SHA512_Update
#define SHA512_Final md_SHA512_Final
#define SHA512_Transform md_SHA512_Transform
#define SHA512 md_SHA512
