# Generated by scripts/update-sources.sh from adv_cmds.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <adv_cmds>/adv_cmds.xcodeproj/project.pbxproj <tool>
#
# One attribute per target. Paths are relative to the adv_cmds source root.
{
  cap_mkdb = [
    "cap_mkdb/cap_mkdb.c"
  ];
  finger = [
    "finger/finger.c"
    "finger/lprint.c"
    "finger/net.c"
    "finger/sprint.c"
    "finger/util.c"
  ];
  gencat = [
    "gencat/gencat.c"
    "gencat/genlib.c"
  ];
  locale = [
    "locale/locale.cc"
  ];
  lsvfs = [
    "lsvfs/lsvfs.c"
  ];
  ps = [
    "ps/fmt.c"
    "ps/keyword.c"
    "ps/nlist.c"
    "ps/print.c"
    "ps/ps.c"
    "ps/tasks.c"
  ];
  stty = [
    "stty/cchar.c"
    "stty/gfmt.c"
    "stty/key.c"
    "stty/modes.c"
    "stty/print.c"
    "stty/stty.c"
    "stty/util.c"
  ];
  tabs = [
    "tabs/tabs.c"
  ];
  tty = [
    "tty/tty.c"
  ];
  whois = [
    "whois/whois.c"
  ];
}
