# Generated by scripts/update-sources.sh from awk.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <awk>/awk.xcodeproj/project.pbxproj <tool>
#
# One attribute per target. Paths are relative to the awk source root.
{
  awk = [
    "src/awkgram.tab.c"
    "src/b.c"
    "src/lex.c"
    "src/lib.c"
    "src/main.c"
    "src/parse.c"
    "src/proctab.c"
    "src/run.c"
    "src/tran.c"
  ];
}
