# Generated by scripts/update-sources.sh from libutil.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <libutil>/libutil.xcodeproj/project.pbxproj util --nix
#
# Paths are relative to the libutil source root.
[
  "ExtentManager.cpp"
  "expand_number.c"
  "getmntopts.c"
  "humanize_number.c"
  "pidfile.c"
  "realhostname.c"
  "reexec_to_match_kernel.c"
  "trimdomain.c"
  "tzbootuuid.c"
  "tzlink.c"
  "wipefs.cpp"
]
