# mkToolchain - hermetic Darwin toolchain from unwrapped clang+lld+llvm binutils.
# Purity via -isysroot (roots all implicit paths), -resource-dir, -fuse-ld=lld.
# No cc-wrapper - it would inject host SDK/NIX_CFLAGS.
{ lib
, runCommand
, writeText
, stdenvNoCC
, llvmPackages
, targetArch
, minOS
}:

let
  clang = llvmPackages.clang-unwrapped;
  lld = llvmPackages.lld;
  llvm = llvmPackages.llvm;

  triple = "${targetArch}-apple-macos${minOS}";

  # ld64/mig/lipo arch name (arm64 not aarch64).
  machoArch = if targetArch == "aarch64" then "arm64" else targetArch;
in

lib.makeOverridable (
{ name ? "minidarwin-toolchain"
  # Header + library search root.
, sysroot
  # null → clang's own resource dir (headers only, no runtime libs).
, resourceDir ? null
, extraCFlags ? [ ]
, extraLDFlags ? [ ]
  # No libclang_rt/libSystem linking (until they exist).
, freestanding ? false
}:

let
  cflags = [
    "-target" triple
    "-isysroot" "${sysroot}"
    "-no-canonical-prefixes"
  ]
  ++ lib.optionals (resourceDir != null) [ "-resource-dir" "${resourceDir}" ]
  ++ extraCFlags;

  ldflags = [
    "-fuse-ld=lld"
    "-B" "${lld}/bin"
    "-Wl,-adhoc_codesign"
    "-Wl,-platform_version,macos,${minOS},${minOS}"
  ]
  ++ lib.optionals freestanding [ "-nostdlib" "-nodefaultlibs" ]
  ++ extraLDFlags;

  driver = binName: realDriver: writeText "minidarwin-${binName}" ''
    #!${stdenvNoCC.shell}
    # Generated by lib/toolchain.nix - do not edit. Link flags withheld for -c/-S/-E (avoids -Werror).
    set -u
    linking=1
    for arg in "$@"; do
      case "$arg" in
        -c|-S|-E|-M|-MM|--analyze|-fsyntax-only) linking=0 ;;
      esac
    done

    # Rewrite build dir out of __FILE__/debug info.
    prefixmap=""
    if [ -n "''${NIX_BUILD_TOP:-}" ]; then
      prefixmap="-ffile-prefix-map=$NIX_BUILD_TOP=/minidarwin-build"
    fi

    cflags=(${lib.escapeShellArgs cflags} -fdebug-compilation-dir=. $prefixmap)
    ldflags=(${lib.escapeShellArgs ldflags})

    if [ "$linking" = 1 ]; then
      exec ${clang}/bin/${realDriver} "''${cflags[@]}" "''${ldflags[@]}" "$@"
    else
      exec ${clang}/bin/${realDriver} "''${cflags[@]}" "$@"
    fi
  '';

  # LLVM binutils under Darwin names (single provenance; llvm-ar deterministic).
  binutilAliases = {
    "ar" = "llvm-ar";
    "ranlib" = "llvm-ranlib";
    "nm" = "llvm-nm";
    "strip" = "llvm-strip";
    "size" = "llvm-size";
    "otool" = "llvm-objdump";
    "objdump" = "llvm-objdump";
    "install_name_tool" = "llvm-install-name-tool";
    "lipo" = "llvm-lipo";
    "libtool" = "llvm-libtool-darwin";
    "dsymutil" = "dsymutil";
    "cxxfilt" = "llvm-cxxfilt";
    "objcopy" = "llvm-objcopy";
  };
in

runCommand name
  {
    passthru = {
      inherit clang lld llvm sysroot resourceDir triple machoArch minOS
        targetArch freestanding cflags ldflags;
    };
    meta.description = "Hermetic Darwin toolchain rooted at ${sysroot}";
  }
  ''
    mkdir -p $out/bin $out/nix-support

    install -m0755 ${driver "cc" "clang"}    $out/bin/cc
    install -m0755 ${driver "c++" "clang++"} $out/bin/c++

    # A bare linker for the rare package that invokes ld directly.
    ln -s ${lld}/bin/ld64.lld $out/bin/ld

    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (alias: real: ''
      if [ -e ${llvm}/bin/${real} ]; then
        ln -s ${llvm}/bin/${real} $out/bin/${alias}
      elif [ -e ${clang}/bin/${real} ]; then
        ln -s ${clang}/bin/${real} $out/bin/${alias}
      fi
    '') binutilAliases)}

    # Setup hook: host-SDK-free env for consumers.
    cat > $out/nix-support/setup-hook <<HOOK
    export MINIDARWIN_SYSROOT=${sysroot}
    export MINIDARWIN_ARCH=${machoArch}
    export MINIDARWIN_TRIPLE=${triple}
    export CC=$out/bin/cc
    export CXX=$out/bin/c++
    export LD=$out/bin/ld
    export AR=$out/bin/ar
    export RANLIB=$out/bin/ranlib
    export NM=$out/bin/nm
    export STRIP=$out/bin/strip
    export LIPO=$out/bin/lipo
    export OTOOL=$out/bin/otool
    export INSTALL_NAME_TOOL=$out/bin/install_name_tool
    export ZERO_AR_DATE=1
    export SOURCE_DATE_EPOCH=\''${SOURCE_DATE_EPOCH:-1}
    HOOK
  ''
)
