# Generated by scripts/update-sources.sh from basic_cmds.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <basic_cmds>/basic_cmds.xcodeproj/project.pbxproj <tool>
#
# One attribute per target. Paths are relative to the basic_cmds source root.
{
  mesg = [
    "mesg/mesg.c"
  ];
  write = [
    "write/write.c"
  ];
}
