# Generated by scripts/update-sources.sh from dyld.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <dyld>/dyld.xcodeproj/project.pbxproj libmach_o --nix
#
# Paths are relative to the dyld source root.
[
  "mach_o/Architecture.cpp"
  "mach_o/Archive.cpp"
  "mach_o/BindOpcodes.cpp"
  "mach_o/ChainedFixups.cpp"
  "mach_o/CompactUnwind.cpp"
  "mach_o/DataInCode.cpp"
  "mach_o/DwarfDebug.cpp"
  "mach_o/Error.cpp"
  "mach_o/ExportsTrie.cpp"
  "mach_o/Fixups.cpp"
  "mach_o/FunctionStarts.cpp"
  "mach_o/FunctionVariants.cpp"
  "mach_o/GradedArchitectures.cpp"
  "mach_o/Image.cpp"
  "mach_o/Instructions.cpp"
  "mach_o/LazyLoadDylib.cpp"
  "mach_o/LinkerOptimizationHints.cpp"
  "mach_o/LoggingStub.cpp"
  "mach_o/Misc.cpp"
  "mach_o/NListSymbolTable.cpp"
  "mach_o/ObjC.cpp"
  "mach_o/Platform.cpp"
  "mach_o/Policy.cpp"
  "mach_o/RebaseOpcodes.cpp"
  "mach_o/SplitSeg.cpp"
  "mach_o/Symbol.cpp"
  "mach_o/Universal.cpp"
  "mach_o/UnsafeHeader.cpp"
  "mach_o/Version32.cpp"
  "mach_o/Version64.cpp"
]
