# Generated by scripts/update-sources.sh from ncurses.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <ncurses>/ncurses.xcodeproj/project.pbxproj <tool>
#
# One attribute per target. Paths are relative to the ncurses source root.
{
  clear = [
    "ncurses/progs/clear.c"
  ];
  infocmp = [
    "ncurses/progs/dump_entry.c"
    "ncurses/progs/infocmp.c"
  ];
  tic = [
    "ncurses/progs/dump_entry.c"
    "ncurses/progs/tic.c"
    "ncurses/progs/tparm_type.c"
    "ncurses/progs/transform.c"
  ];
  toe = [
    "ncurses/progs/toe.c"
  ];
  tput = [
    "ncurses/progs/tparm_type.c"
    "ncurses/progs/tput.c"
    "ncurses/progs/transform.c"
  ];
  tset = [
    "ncurses/progs/transform.c"
    "ncurses/progs/tset.c"
  ];
}
