#!/usr/bin/env python3
"""Stub for `dtrace -h`: generates PROVIDER_PROBE macros with every probe disabled.

Usage: dtrace-provider-stub.py <provider.d> <out.h>
"""
import re
import sys


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__.strip().splitlines()[2])
    src, dst = sys.argv[1], sys.argv[2]

    text = open(src).read()

    # Split into provider blocks; macro names include provider.
    blocks = re.findall(r"\bprovider\s+(\w+)\s*\{(.*?)\n\}", text, re.S)
    if not blocks:
        sys.exit(f"dtrace-provider-stub: no provider declaration in {src}")

    probes = []
    for pname, body in blocks:
        # Argument types don't matter, only arity.
        for name, args in re.findall(r"\bprobe\s+(\w+)\s*\(([^)]*)\)\s*;",
                                     body):
            probes.append((pname, name, args))
    if not probes:
        sys.exit(f"dtrace-provider-stub: no probes found in {src}")

    guard = "_" + blocks[0][0].upper() + "PROVIDER_STUB_H"
    out = [
        f"/* Generated by scripts/dtrace-provider-stub.py from {src.split('/')[-1]}.",
        " * Stands in for `dtrace -h`; every probe is compiled out. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
    ]
    for pname, name, args in probes:
        nargs = len([a for a in args.split(",")
                     if a.strip() and a.strip() != "void"])
        params = ",".join(f"arg{i}" for i in range(nargs))
        # dtrace mangles timer__configure → DISPATCH_TIMER_CONFIGURE.
        macro = f"{pname.upper()}_{name.upper().replace('__', '_')}"
        out.append(f"#define {macro}({params})")
        out.append(f"#define {macro}_ENABLED() (0)")
    out += ["", f"#endif /* {guard} */", ""]

    with open(dst, "w") as f:
        f.write("\n".join(out))
    print(f"[minidarwin] {dst.split('/')[-1]}: {len(probes)} probes stubbed",
          file=sys.stderr)


if __name__ == "__main__":
    main()
