#!/usr/bin/env bash
# Refresh lib/sources.nix tags + regenerate pbxproj-derived file lists.
# Manual step - review output (same OS release, not "newest of each").
# Usage: scripts/update-sources.sh [--check] [project ...]
set -euo pipefail

cd "$(dirname "$0")/.."

check_only=0
if [ "${1-}" = "--check" ]; then check_only=1; shift; fi

projects=("$@")
if [ "${#projects[@]}" -eq 0 ]; then
  # Every project named in lib/sources.nix.
  mapfile -t projects < <(
    sed -n 's/^  [A-Za-z_]* = apple "\([^"]*\)".*/\1/p' lib/sources.nix
  )
fi

changed=0

for repo in "${projects[@]}"; do
  current=$(sed -n "s/.*apple \"$repo\" \"\([^\"]*\)\".*/\1/p" lib/sources.nix | head -1)

  # git ls-remote: no rate limit, no token.
  latest=$(git ls-remote --tags --refs \
             "https://github.com/apple-oss-distributions/$repo" 2>/dev/null |
           sed 's|.*refs/tags/||' | sort -V | tail -1)

  if [ -z "$latest" ]; then
    echo "warn: no tags found for $repo" >&2
    continue
  fi

  if [ "$latest" = "$current" ]; then
    printf '  %-24s %s (up to date)\n' "$repo" "$current"
    continue
  fi

  changed=1
  printf '  %-24s %s -> %s\n' "$repo" "$current" "$latest"

  if [ "$check_only" = 1 ]; then continue; fi

  hash=$(nix flake prefetch --json \
           "github:apple-oss-distributions/$repo/$latest" |
         python3 -c 'import sys,json; print(json.load(sys.stdin)["hash"])')

  # Rewrite tag and hash for this project.
  python3 - "$repo" "$latest" "$hash" <<'PY'
import re, sys
repo, tag, hash_ = sys.argv[1:4]
path = "lib/sources.nix"
src = open(path).read()
pat = re.compile(
    r'(apple "%s" ")[^"]*("\s*\n\s*")[^"]*(")' % re.escape(repo))
new, n = pat.subn(lambda m: m.group(1) + tag + m.group(2) + hash_ + m.group(3), src)
if n != 1:
    sys.exit(f"expected exactly one entry for {repo}, found {n}")
open(path, "w").write(new)
PY
done

if [ "$check_only" = 1 ]; then
  exit $changed
fi

if [ "$changed" = 1 ]; then
  echo
  echo "Regenerating derived file lists..."

  xnu=$(nix-build --no-out-link -E \
    'with import <nixpkgs> {};
     (import ./. { pkgs = import <nixpkgs> {}; }).sources.xnu')

  {
    echo "# Generated by scripts/update-sources.sh from xnu's Libsyscall.xcodeproj."
    echo "# Regenerate with:"
    echo "#   scripts/pbxproj-sources.py <xnu>/libsyscall/Libsyscall.xcodeproj/project.pbxproj \\"
    echo "#     Libsyscall_static --nix"
    echo "#"
    echo "# Paths are relative to xnu/libsyscall. .defs entries are mig inputs, not"
    echo "# compiler inputs: pkgs/libsystem/libsyscall.nix turns each into a User.c."
    echo "["
    for target in Libsyscall_static Libsyscall_dynamic; do
      python3 scripts/pbxproj-sources.py \
        "$xnu/libsyscall/Libsyscall.xcodeproj/project.pbxproj" "$target" |
        sed 's/^/  "/;s/$/"/'
    done
    echo "]"
  } > pkgs/libsystem/libsyscall-sources.nix

  # Other pbxproj-derived lists. libplatform has no .xcodeproj - its file list is its directory layout.
  gen_sources() { # <attr> <project-relative .xcodeproj path> <target> <out>
    local attr="$1" proj="$2" target="$3" out="$4" src
    src=$(nix-build --no-out-link -E \
      "(import ./. { pkgs = import <nixpkgs> {}; }).sources.$attr")
    {
      echo "# Generated by scripts/update-sources.sh from $(basename "$(dirname "$proj")")."
      echo "# Regenerate with:"
      echo "#   scripts/pbxproj-sources.py <$attr>/$proj $target --nix"
      echo "#"
      echo "# Paths are relative to the $attr source root."
      echo "["
      python3 scripts/pbxproj-sources.py "$src/$proj" "$target" |
        sed 's/^/  "/;s/$/"/'
      echo "]"
    } > "$out"
  }

  gen_sources libpthread libpthread.xcodeproj/project.pbxproj \
    libsystem_pthread pkgs/libsystem/libpthread-sources.nix
  gen_sources libmalloc libmalloc.xcodeproj/project.pbxproj \
    libsystem_malloc pkgs/libsystem/libmalloc-sources.nix

  # Stage 5: dyld uses synchronized folders (Xcode 16); dyld-mighty is the real target.
  gen_sources dyld dyld.xcodeproj/project.pbxproj \
    dyld-mighty pkgs/dyld/dyld-sources.nix
  gen_sources dyld dyld.xcodeproj/project.pbxproj \
    libmach_o pkgs/dyld/libmach-o-sources.nix

  # Stage 6: the libraries sh links for line editing, and ls's libutil.
  gen_sources ncurses ncurses.xcodeproj/project.pbxproj \
    libncurses pkgs/ncurses/ncurses-sources.nix
  gen_sources ncurses ncurses.xcodeproj/project.pbxproj \
    tic_static pkgs/ncurses/tic-sources.nix
  gen_sources libedit libedit.xcodeproj/project.pbxproj \
    libedit pkgs/libedit/libedit-sources.nix
  gen_sources libutil libutil.xcodeproj/project.pbxproj \
    util pkgs/libutil/libutil-sources.nix

  # Stage 6: *_cmds projects, one attribute per tool target (pkgs/cmds/mk-cmds.nix).
  gen_cmds() { # <attr> <out> <target>...
    local attr="$1" out="$2" src tool; shift 2
    src=$(nix-build --no-out-link -E \
      "(import ./. { pkgs = import <nixpkgs> {}; }).sources.$attr")
    {
      echo "# Generated by scripts/update-sources.sh from $attr.xcodeproj."
      echo "# Regenerate with:"
      echo "#   scripts/pbxproj-sources.py <$attr>/$attr.xcodeproj/project.pbxproj <tool>"
      echo "#"
      echo "# One attribute per target. Paths are relative to the $attr source root."
      echo "{"
      for tool in "$@"; do
        echo "  $tool = ["
        python3 scripts/pbxproj-sources.py \
          "$src/$attr.xcodeproj/project.pbxproj" "$tool" |
          sed 's/^/    "/;s/$/"/'
        echo "  ];"
      done
      echo "}"
    } > "$out"
  }

  gen_cmds shell_cmds pkgs/shell-cmds/shell-cmds-sources.nix \
    echo false find hostname id pwd realpath sh true uname who yes
  gen_cmds file_cmds pkgs/file-cmds/file-cmds-sources.nix \
    chflags chmod chown cp du ln ls mkdir mv stat truncate xattr

  echo
  echo "Now re-run the build. Header layout and unifdef flags change between"
  echo "releases more often than you would like."
fi
