# Generated by scripts/update-sources.sh from libedit.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <libedit>/libedit.xcodeproj/project.pbxproj libedit --nix
#
# Paths are relative to the libedit source root.
[
  "local/fcns.c"
  "local/help.c"
  "local/historyn.c"
  "local/tokenizern.c"
  "src/chared.c"
  "src/chartype.c"
  "src/common.c"
  "src/el.c"
  "src/eln.c"
  "src/emacs.c"
  "src/filecomplete.c"
  "src/hist.c"
  "src/history.c"
  "src/keymacro.c"
  "src/map.c"
  "src/parse.c"
  "src/prompt.c"
  "src/read.c"
  "src/readline.c"
  "src/refresh.c"
  "src/search.c"
  "src/sig.c"
  "src/terminal.c"
  "src/tokenizer.c"
  "src/tty.c"
  "src/unvis.c"
  "src/vi.c"
  "src/vis.c"
  "src/wcsdup.c"
]
