# Generated by scripts/update-sources.sh from patch_cmds.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <patch_cmds>/patch_cmds.xcodeproj/project.pbxproj <tool>
#
# One attribute per target. Paths are relative to the patch_cmds source root.
{
  cmp = [
    "cmp/cmp.c"
    "cmp/link.c"
    "cmp/misc.c"
    "cmp/regular.c"
    "cmp/special.c"
  ];
  diff = [
    "diff/diff.c"
    "diff/diff_atomize_text.c"
    "diff/diff_main.c"
    "diff/diff_myers.c"
    "diff/diff_output.c"
    "diff/diff_output_edscript.c"
    "diff/diff_output_plain.c"
    "diff/diff_output_unidiff.c"
    "diff/diff_patience.c"
    "diff/diffdir.c"
    "diff/diffreg.c"
    "diff/diffreg_new.c"
    "diff/pr.c"
    "diff/recallocarray.c"
    "diff/xmalloc.c"
  ];
  diff3 = [
    "diff3/diff3.c"
    "diff3/xmalloc.c"
  ];
  diffstat = [
    "diffstat/diffstat.c"
  ];
  patch = [
    "patch/backupfile.c"
    "patch/inp.c"
    "patch/mkpath.c"
    "patch/patch.c"
    "patch/pch.c"
    "patch/util.c"
    "patch/vcs.c"
  ];
  sdiff = [
    "sdiff/edit.c"
    "sdiff/extern.h"
    "sdiff/sdiff.c"
  ];
}
