# Generated by scripts/update-sources.sh from misc_cmds.xcodeproj.
# Regenerate with:
#   scripts/pbxproj-sources.py <misc_cmds>/misc_cmds.xcodeproj/project.pbxproj <tool>
#
# One attribute per target. Paths are relative to the misc_cmds source root.
{
  cal = [
    "ncal/calendar.c"
    "ncal/easter.c"
    "ncal/ncal.c"
  ];
  calendar = [
    "calendar/calendar.c"
    "calendar/dates.c"
    "calendar/day.c"
    "calendar/events.c"
    "calendar/io.c"
    "calendar/locale.c"
    "calendar/ostern.c"
    "calendar/parsedata.c"
    "calendar/paskha.c"
    "calendar/pom.c"
    "calendar/sunpos.c"
  ];
  ncal = [
    "ncal/calendar.c"
    "ncal/easter.c"
    "ncal/ncal.c"
  ];
  tsort = [
    "tsort/tsort.c"
  ];
  units = [
    "units/units.c"
  ];
}
